; Режим отладки: точки останова, пошаговое выполнение
xdebug.mode = debug

; Начинать сессию отладки при каждом запросе
xdebug.start_with_request = yes

; Куда стучаться: host.docker.internal — это твой Mac со стороны контейнера
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003

xdebug.idekey = PHPSTORM

; Лог пригодится, если PhpStorm не поймает соединение
xdebug.log = /tmp/xdebug.log
xdebug.log_level = 7
